remote_theme: poole/lanyon

# Setup
title:               hapagirl
tagline:             'hapagirl knitting'
description:         'knitting, nerdy things and medieval history'
url:                 https://hapagirl1066.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kalani Craig
  url:               https://twitter.com/kalanicraig
  email:             kalanicraig@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
