# Your name to show in the footer
author: Kalani Craig

# Title of your website
title: 'hapagirl.com'

# Title of your website
subtitle: 'knitting, coding, making and other related stuff'

# Maximum of 150 characters for SEO-purposes.
description: 'knitting, coding, making and other related stuff for nerds, with occasional history'

# The credits show up in the includes/_footer.html
# Main author of the website
# See > authors.yml

author: KalaniCraig

authorname : Kalani Craig
email : kalani [at] hapagirl.com
twitter : hapagirl
github : hapagirl1066
orcid : 
googlescholar : 

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: ''
baseurl: ''

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.url }}{{ site.baseurl }}{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.url }}{{ site.baseurl }}{{ site.urlimg }}image.jpg)
#
urlimg: '/assets/img/'
destination: docs/
permalink:   /:categories/:title/
logo: logo.svg

year : 2022
markdown : kramdown
exclude :
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - pages/PagesOld
    - INSTALL.md
include: ['_pages']

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
sitelogo: "logo.svg"

##############################################
# ORGANIZING YOUR COLLECTION
#---------------------
# These collections take the basic files you put together for each item in your collection and auto-group and display them.
# This takes each item in your archive collection and displays it
collections:
  patterns:
    output: true
    permalink: /:collection/:path:output_ext
    title: true

plugins:
  - jekyll-seo-tag

google_analytics_tracking_id: UA-11680223-1
google_g4_analytics_id: G-LVREG1Y1DT

